### ADD LIBRARY

In [2]:
import os
import io
import cv2
import imageio
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers, Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report


### VARIABLE DECLARATION

In [3]:
DATASET_NAME = "violence_and_nonviolence_videos"
BATCH_SIZE = 32
AUTO = tf.data.AUTOTUNE
INPUT_SHAPE = (36, 28, 28, 3)
NUM_CLASSES = 2
LABELS = ["no","fi"]

# OPTIMIZER
LEARNING_RATE = 0.0001
WEIGHT_DECAY = 0.00001

# TRAINING
EPOCHS = 100

# TUBELET EMBEDDING
PATCH_SIZE = (8, 8, 8)
NUM_PATCHES = (INPUT_SHAPE[0] // PATCH_SIZE[0]) ** 2

# ViViT ARCHITECTURE
LAYER_NORM_EPS = 1e-6
PROJECTION_DIM = 128
NUM_HEADS = 8
NUM_LAYERS = 8

### DATASET PREPARATION

In [4]:
data_path = "C:/Users/Emirhan/Downloads/data"
classes = os.listdir(data_path)

videos = []
labels = []

for cls in classes:
    cls_path = os.path.join(data_path, cls)
    files = os.listdir(cls_path)
    for video in os.listdir(cls_path):
        video_path = os.path.join(cls_path, video)
        videos.append(video_path)
        label = os.path.basename(video_path).split('_')[0][0:2]
        if label not in LABELS:
            continue
        labels.append(label)



In [5]:
labels = np.array(labels)
videos = np.array(videos)

In [6]:
print(labels)

['no' 'no' 'no' ... 'fi' 'fi' 'fi']


#### ONE-HOT ENCODING

In [7]:
encoder = OneHotEncoder(sparse=False)
labels = encoder.fit_transform(np.array(labels).reshape(-1, 1))

print(labels)


[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


c:\Users\Emirhan\anaconda3\envs\tfenv\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


### DATA PREPROCESSING

In [8]:
temp_videos = videos
temp_labels = labels

X_train, X_test, y_train1, y_test1 = train_test_split(temp_videos, temp_labels, test_size=0.20,random_state=1)

# Bu kısım prediction kısmında test verilerini video halinde görüntüleyebilmek için yazılmıştır.


In [9]:
video_paths = videos

# Fındıng minimum frame count
min_frame_count = float('inf')

for video_path in video_paths:
    cap = cv2.VideoCapture(video_path)
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if frame_count < min_frame_count:
        min_frame_count = frame_count


frames = []

for video_path in video_paths:
    cap = cv2.VideoCapture(video_path)
    selected_frames = []
    for i in range(min_frame_count):
        ret, frame = cap.read()
        if ret:
            frame = cv2.resize(frame, (28,28))
            selected_frames.append(frame)
    frames.append(np.array(selected_frames))

frames_array = np.array(frames)


print(frames_array.shape)


(2000, 36, 28, 28, 3)


In [10]:
X_train_frames, X_test_frames, y_train, y_test = train_test_split(frames_array, labels, test_size=0.25,random_state=1)

In [11]:
X_train_frames, X_val_frames, y_train, y_val = train_test_split(X_train_frames, y_train, test_size=0.15, random_state=1)

In [12]:
X_train_frames

array([[[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         ...,

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],


        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
     

In [13]:
len(X_train_frames)

1275

In [14]:
len(X_test_frames)

500

In [15]:
len(X_val_frames)

225

##### DATA STANDARDIZATION

In [16]:
X_train_frames = X_train_frames/255
X_test_frames = X_test_frames/255
X_val_frames = X_val_frames/255

In [17]:
@tf.function
def preprocess(frames: tf.Tensor, label: tf.Tensor):
    """Preprocess the frames tensors and parse the labels."""
    # Preprocess images
    frames = tf.image.convert_image_dtype(
        frames[
            ..., tf.newaxis
        ],  # The new axis is to help for further processing with Conv3D layers
        tf.float32,
    )
    # Parse label
    label = tf.cast(label, tf.float32)
    return frames, label


def prepare_dataloader(
    videos: np.ndarray,
    labels: np.ndarray,
    loader_type: str = "train",
    batch_size: int = BATCH_SIZE,
):
    """Utility function to prepare the dataloader."""
    dataset = tf.data.Dataset.from_tensor_slices((videos, labels))

    if loader_type == "train":
        dataset = dataset.shuffle(BATCH_SIZE * 2)

    dataloader = (
        dataset.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )
    return dataloader


trainloader = prepare_dataloader(X_train_frames, y_train, "train")
validloader = prepare_dataloader(X_val_frames, y_val, "valid")
testloader = prepare_dataloader(X_test_frames, y_test, "test")

In [18]:
testloader

<PrefetchDataset element_spec=(TensorSpec(shape=(None, 36, 28, 28, 3, 1), dtype=tf.float32, name=None), TensorSpec(shape=(None, 2), dtype=tf.float32, name=None))>

### BUILDING THE MODEL

In [19]:
# TUBELET EMBEDDING

class TubeletEmbedding(layers.Layer):
    def __init__(self, embed_dim, patch_size, **kwargs):
        super().__init__(**kwargs)
        self.projection = layers.Conv3D(
            filters=embed_dim,
            kernel_size=patch_size,
            strides=patch_size,
            padding="VALID",
        )
        self.flatten = layers.Reshape(target_shape=(-1, embed_dim))

    def call(self, videos):
        projected_patches = self.projection(videos)
        flattened_patches = self.flatten(projected_patches)
        return flattened_patches


In [20]:
# POSITIONAL 

class PositionalEncoder(layers.Layer):
    def __init__(self, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim

    def build(self, input_shape):
        _, num_tokens, _ = input_shape
        self.position_embedding = layers.Embedding(
            input_dim=num_tokens, output_dim=self.embed_dim
        )
        self.positions = tf.range(start=0, limit=num_tokens, delta=1)

    def call(self, encoded_tokens):
        # Encode the positions and add it to the encoded tokens
        encoded_positions = self.position_embedding(self.positions)
        encoded_tokens = encoded_tokens + encoded_positions
        return encoded_tokens

In [21]:
def create_vivit_classifier(
    tubelet_embedder,
    positional_encoder,
    input_shape=INPUT_SHAPE,
    transformer_layers=NUM_LAYERS,
    num_heads=NUM_HEADS,
    embed_dim=PROJECTION_DIM,
    layer_norm_eps=LAYER_NORM_EPS,
    num_classes=NUM_CLASSES,
):
    # Get the input layer
    inputs = layers.Input(shape=input_shape)
    # Create patches.
    patches = tubelet_embedder(inputs)
    # Encode patches.
    encoded_patches = positional_encoder(patches)

    # Create multiple layers of the Transformer block.
    for _ in range(transformer_layers):
        # Layer normalization and MHSA
        x1 = layers.LayerNormalization(epsilon=1e-6)(encoded_patches)
        attention_output = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim // num_heads, dropout=0.1
        )(x1, x1)

        # Skip connection
        x2 = layers.Add()([attention_output, encoded_patches])

        # Layer Normalization and MLP
        x3 = layers.LayerNormalization(epsilon=1e-6)(x2)
        x3 = keras.Sequential(
            [
                layers.Dense(units=embed_dim * 4, activation=tf.nn.gelu),
                layers.Dense(units=embed_dim, activation=tf.nn.gelu),
            ]
        )(x3)

        # Skip connection
        encoded_patches = layers.Add()([x3, x2])

    # Layer normalization and Global average pooling.
    representation = layers.LayerNormalization(epsilon=layer_norm_eps)(encoded_patches)
    representation = layers.GlobalAvgPool1D()(representation)

    # Classify outputs.
    outputs = layers.Dense(units=num_classes, activation="softmax")(representation)

    # Create the Keras model.
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model

### MODEL TRAINING

In [22]:
def run_experiment():
    # Initialize model
    model = create_vivit_classifier(
        tubelet_embedder=TubeletEmbedding(
            embed_dim=PROJECTION_DIM, patch_size=PATCH_SIZE
        ),
        positional_encoder=PositionalEncoder(embed_dim=PROJECTION_DIM),
    )

    # Compile the model with the optimizer, loss function
    # and the metrics.
    optimizer = keras.optimizers.Adam(learning_rate=LEARNING_RATE)
    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=['accuracy'
        ],
    )

    # Train the model.
    _ = model.fit(trainloader, epochs=EPOCHS, validation_data=validloader)


    return model


model = run_experiment()

Epoch 1/100
40/40 [==============================] - 13s 89ms/step - loss: 0.7528 - accuracy: 0.5451 - val_loss: 0.6688 - val_accuracy: 0.6356
Epoch 2/100
40/40 [==============================] - 2s 61ms/step - loss: 0.6954 - accuracy: 0.5522 - val_loss: 0.7446 - val_accuracy: 0.4711
Epoch 3/100
40/40 [==============================] - 3s 63ms/step - loss: 0.6777 - accuracy: 0.5647 - val_loss: 0.6338 - val_accuracy: 0.6356
Epoch 4/100
40/40 [==============================] - 3s 67ms/step - loss: 0.6165 - accuracy: 0.6627 - val_loss: 0.5850 - val_accuracy: 0.6844
Epoch 5/100
40/40 [==============================] - 3s 66ms/step - loss: 0.5853 - accuracy: 0.6816 - val_loss: 0.6076 - val_accuracy: 0.6756
Epoch 6/100
40/40 [==============================] - 3s 65ms/step - loss: 0.5520 - accuracy: 0.6941 - val_loss: 0.5706 - val_accuracy: 0.6889
Epoch 7/100
40/40 [==============================] - 3s 65ms/step - loss: 0.5266 - accuracy: 0.7114 - val_loss: 0.5786 - val_accuracy: 0.6889
Epoch

In [23]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 36, 28, 28,  0           []                               
                                 3)]                                                              
                                                                                                  
 tubelet_embedding (TubeletEmbe  (None, 36, 128)     196736      ['input_1[0][0]']                
 dding)                                                                                           
                                                                                                  
 positional_encoder (Positional  (None, 36, 128)     4608        ['tubelet_embedding[0][0]']      
 Encoder)                                                                                     

### EVALUATE THE MODEL

In [24]:
x_test = X_test_frames

y_pred = model.predict(x_test)

print(y_pred) # (num_samples, num_classes)


16/16 [==============================] - 1s 23ms/step
[[4.25325464e-09 1.00000000e+00]
 [9.99967337e-01 3.26153386e-05]
 [9.99996543e-01 3.44172417e-06]
 [1.00000000e+00 2.09879381e-09]
 [1.00000000e+00 1.11982699e-08]
 [1.00000000e+00 7.66504105e-09]
 [1.00000000e+00 1.57946829e-08]
 [3.86870491e-09 1.00000000e+00]
 [9.99999881e-01 1.31009642e-07]
 [3.49544704e-01 6.50455236e-01]
 [1.00000000e+00 4.06068530e-08]
 [9.97712255e-01 2.28770962e-03]
 [5.40340086e-03 9.94596601e-01]
 [1.00000000e+00 3.09959236e-09]
 [8.43023074e-08 9.99999881e-01]
 [9.61323202e-01 3.86768505e-02]
 [4.88775953e-09 1.00000000e+00]
 [1.00000000e+00 2.24737473e-08]
 [9.47501838e-01 5.24981394e-02]
 [1.00000000e+00 9.45243439e-09]
 [1.00000000e+00 1.50588542e-09]
 [1.00000000e+00 3.65374508e-09]
 [3.96620749e-07 9.99999642e-01]
 [1.08653140e-08 1.00000000e+00]
 [3.82402874e-08 1.00000000e+00]
 [6.11119733e-09 1.00000000e+00]
 [9.99999642e-01 3.05867189e-07]
 [9.99979973e-01 2.00696413e-05]
 [1.62190091e-07 9.999

In [25]:
predictions = y_pred > 0.5

In [26]:
predictions = predictions.astype(float)
predictions

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.

In [27]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.79      0.80      0.79       245
           1       0.80      0.79      0.80       255

   micro avg       0.79      0.79      0.79       500
   macro avg       0.79      0.79      0.79       500
weighted avg       0.79      0.79      0.79       500
 samples avg       0.79      0.79      0.79       500



In [28]:
y_test

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.

### PREDICTIONS

In [29]:

def video_show(single_video):
    
    video_path = single_video

    cap = cv2.VideoCapture(video_path)

    gif_frames = []

    while True:
     
        ret, frame = cap.read()

        if not ret:
            break

        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        gif_frames.append(frame_rgb)

    cap.release()

    imageio.mimsave("video.gif", gif_frames, fps=30)

def predict(frames):
    frames = [frames] 
    frames = np.array(frames)
    y_pred = model.predict(frames)

   
    predictions = y_pred > 0.5
    print(predictions)  # (num_samples, num_classes)


In [30]:
video_show(X_test[140])
predict(X_test_frames[140])

1/1 [==============================] - 0s 35ms/step
[[False  True]]
